micronaut:
  application:
    name: micronautBasics
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'com.stark.domain'
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.hbm2ddl.show_sql: true
jpa.default.properties.hibernate.hbm2ddl.format_sql: true
netty:
  default:
    allocator:
      max-order: 3
